- name: docker gpg key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: add docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable

- name: install docker
  apt: name=docker-ce
